# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - id: binary
    main: ./cmd/sbomlyze
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/rezmoss/sbomlyze/internal/version.Version={{.Version}}
      - -X github.com/rezmoss/sbomlyze/internal/version.Commit={{.Commit}}
      - -X github.com/rezmoss/sbomlyze/internal/version.Date={{.Date}}
      - -X github.com/rezmoss/sbomlyze/internal/version.BuildSource=binaryRelease

  - id: binary-arm
    main: ./cmd/sbomlyze
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
      - -X github.com/rezmoss/sbomlyze/internal/version.Version={{.Version}}
      - -X github.com/rezmoss/sbomlyze/internal/version.Commit={{.Commit}}
      - -X github.com/rezmoss/sbomlyze/internal/version.Date={{.Date}}
      - -X github.com/rezmoss/sbomlyze/internal/version.BuildSource=binaryRelease

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if .Arm }}{{ .Arch }}v{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

# Linux packages (.deb, .rpm, .apk)
nfpms:
  - id: packages
    package_name: sbomlyze
    vendor: rezmoss
    homepage: https://github.com/rezmoss/sbomlyze
    maintainer: rezmoss <rezmoss@users.noreply.github.com>
    description: A fast, reliable SBOM diff and analysis tool
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/sbomlyze/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/sbomlyze/README.md

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bump"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: rezmoss
    name: sbomlyze
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - repository:
      owner: rezmoss
      name: homebrew-sbomlyze
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/rezmoss/sbomlyze"
    description: "A fast, reliable SBOM diff and analysis tool"
    license: "Apache-2.0"
    test: |
      system "#{bin}/sbomlyze", "--version"
    install: |
      bin.install "sbomlyze"