package output

import (
	"fmt"
	"html"
	"path/filepath"
	"strings"
	"time"

	"github.com/rezmoss/sbomlyze/internal/analysis"
	"github.com/rezmoss/sbomlyze/internal/policy"
	"github.com/rezmoss/sbomlyze/internal/sbom"
)

const htmlStyles = `
<style>
  :root {
    --bg: #ffffff; --fg: #1a1a2e; --border: #e0e0e0;
    --accent: #0f3460; --accent-light: #e8eef6;
    --green: #2d6a4f; --green-bg: #d8f3dc;
    --red: #9b2226; --red-bg: #fde8e8;
    --yellow: #b08000; --yellow-bg: #fff8e1;
    --blue: #1565c0; --blue-bg: #e3f2fd;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: var(--fg); background: var(--bg); line-height: 1.6; padding: 2rem; max-width: 1100px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; color: var(--accent); }
  h2 { font-size: 1.15rem; margin: 1.5rem 0 0.5rem; padding-bottom: 0.25rem; border-bottom: 2px solid var(--accent); color: var(--accent); }
  h3 { font-size: 1rem; margin: 1rem 0 0.4rem; color: var(--fg); }
  .meta { color: #666; font-size: 0.85rem; margin-bottom: 1.5rem; }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0 1rem; font-size: 0.9rem; }
  th, td { padding: 0.45rem 0.75rem; text-align: left; border: 1px solid var(--border); }
  th { background: var(--accent-light); font-weight: 600; }
  tr:nth-child(even) { background: #fafafa; }
  .badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 3px; font-size: 0.8rem; font-weight: 600; }
  .badge-error { background: var(--red-bg); color: var(--red); }
  .badge-warn { background: var(--yellow-bg); color: var(--yellow); }
  .badge-ok { background: var(--green-bg); color: var(--green); }
  .badge-info { background: var(--blue-bg); color: var(--blue); }
  .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 0.75rem; margin: 0.75rem 0; }
  .summary-card { border: 1px solid var(--border); border-radius: 6px; padding: 0.75rem; text-align: center; }
  .summary-card .num { font-size: 1.75rem; font-weight: 700; }
  .summary-card .label { font-size: 0.8rem; color: #666; }
  .finding { padding: 0.4rem 0; }
  .section { margin-bottom: 0.5rem; }
  details { margin: 0.5rem 0; }
  summary { cursor: pointer; font-weight: 600; padding: 0.4rem 0; }
  footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: 0.8rem; color: #999; }
</style>`

// GenerateHTML creates a self-contained HTML diff report.
func GenerateHTML(result analysis.DiffResult, violations []policy.Violation, overview analysis.DiffOverview, findings analysis.KeyFindings) string {
	var sb strings.Builder

	sb.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	sb.WriteString("<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
	sb.WriteString("<title>SBOM Diff Report</title>\n")
	sb.WriteString(htmlStyles)
	sb.WriteString("\n</head>\n<body>\n")

	sb.WriteString("<h1>📦 SBOM Diff Report</h1>\n")
	sb.WriteString(fmt.Sprintf("<p class=\"meta\">Generated by <a href=\"https://github.com/rezmoss/sbomlyze\">sbomlyze</a> · %s</p>\n",
		html.EscapeString(time.Now().UTC().Format(time.RFC3339))))

	// Overview table
	writeHTMLOverview(&sb, overview)

	// Summary cards
	writeHTMLSummaryCards(&sb, result)

	// Key findings
	if len(findings.Findings) > 0 {
		writeHTMLFindings(&sb, findings)
	}

	// Drift summary
	if result.DriftSummary != nil {
		writeHTMLDriftSummary(&sb, result)
	}

	// Dependency depth
	if result.Dependencies != nil && result.Dependencies.DepthSummary != nil {
		writeHTMLDepthSummary(&sb, result)
	}

	// Policy violations
	if len(violations) > 0 {
		writeHTMLViolations(&sb, violations)
	}

	// Component tables (collapsible)
	if len(result.Added) > 0 {
		writeHTMLComponentSection(&sb, "➕ Added Components", result.Added, "added")
	}
	if len(result.Removed) > 0 {
		writeHTMLComponentSection(&sb, "➖ Removed Components", result.Removed, "removed")
	}
	if len(result.Changed) > 0 {
		writeHTMLChangedSection(&sb, result.Changed)
	}

	sb.WriteString("<footer>Report produced by <strong>sbomlyze</strong> — SBOM diff &amp; analysis tool</footer>\n")
	sb.WriteString("</body>\n</html>\n")

	return sb.String()
}

// GenerateHTMLStats creates a self-contained HTML statistics report for a single SBOM.
func GenerateHTMLStats(stats analysis.Stats, info sbom.SBOMInfo, findings analysis.KeyFindings) string {
	var sb strings.Builder

	sb.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	sb.WriteString("<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
	sb.WriteString("<title>SBOM Statistics Report</title>\n")
	sb.WriteString(htmlStyles)
	sb.WriteString("\n</head>\n<body>\n")

	sb.WriteString("<h1>📦 SBOM Statistics Report</h1>\n")
	sb.WriteString(fmt.Sprintf("<p class=\"meta\">Generated by <a href=\"https://github.com/rezmoss/sbomlyze\">sbomlyze</a> · %s</p>\n",
		html.EscapeString(time.Now().UTC().Format(time.RFC3339))))

	// Scan context
	sb.WriteString("<h2>Scan Context</h2>\n<table>\n")
	sb.WriteString("<tr><th>Field</th><th>Value</th></tr>\n")
	writeHTMLRow(&sb, "Tool", orNone(info.ToolName))
	writeHTMLRow(&sb, "OS", orNone(info.OSPrettyName))
	writeHTMLRow(&sb, "Source", orNone(info.SourceName))
	if info.SchemaVersion != "" {
		writeHTMLRow(&sb, "Schema", info.SchemaVersion)
	}
	sb.WriteString("</table>\n")

	// Summary
	sb.WriteString("<div class=\"summary-grid\">\n")
	writeHTMLCard(&sb, fmt.Sprintf("%d", stats.TotalComponents), "Total Components")
	writeHTMLCard(&sb, fmt.Sprintf("%d", stats.WithHashes), "With Hashes")
	writeHTMLCard(&sb, fmt.Sprintf("%d", stats.TotalComponents-stats.WithoutLicense), "With License")
	writeHTMLCard(&sb, fmt.Sprintf("%d", stats.DuplicateCount), "Duplicates")
	sb.WriteString("</div>\n")

	// Findings
	if len(findings.Findings) > 0 {
		writeHTMLFindings(&sb, findings)
	}

	// Package types
	if len(stats.ByType) > 0 {
		sb.WriteString("<h2>By Package Type</h2>\n<table>\n")
		sb.WriteString("<tr><th>Type</th><th>Count</th></tr>\n")
		for _, t := range analysis.SortedKeys(stats.ByType) {
			writeHTMLRow(&sb, t, fmt.Sprintf("%d", stats.ByType[t]))
		}
		sb.WriteString("</table>\n")
	}

	// Licenses
	if len(stats.ByLicense) > 0 {
		sb.WriteString("<h2>Top Licenses</h2>\n<table>\n")
		sb.WriteString("<tr><th>License</th><th>Count</th></tr>\n")
		sorted := analysis.SortedByValue(stats.ByLicense)
		shown := 0
		for _, lic := range sorted {
			if shown >= 15 {
				fmt.Fprintf(&sb, "<tr><td colspan=\"2\"><em>…and %d more</em></td></tr>\n", len(sorted)-15)
				break
			}
			writeHTMLRow(&sb, lic, fmt.Sprintf("%d", stats.ByLicense[lic]))
			shown++
		}
		sb.WriteString("</table>\n")
	}

	// License categories
	if stats.LicenseCategories != nil {
		lc := stats.LicenseCategories
		sb.WriteString("<h2>License Categories</h2>\n<table>\n")
		sb.WriteString("<tr><th>Category</th><th>Count</th></tr>\n")
		writeHTMLRow(&sb, "Permissive", fmt.Sprintf("%d", lc.Permissive))
		writeHTMLRow(&sb, "Copyleft", fmt.Sprintf("%d", lc.Copyleft))
		writeHTMLRow(&sb, "Public Domain", fmt.Sprintf("%d", lc.PublicDomain))
		writeHTMLRow(&sb, "Unknown", fmt.Sprintf("%d", lc.Unknown))
		sb.WriteString("</table>\n")
	}

	// Duplicates
	if stats.DuplicateCount > 0 {
		sb.WriteString("<h2>⚠️ Duplicates</h2>\n<table>\n")
		sb.WriteString("<tr><th>Package</th><th>Versions</th></tr>\n")
		for _, d := range stats.Duplicates {
			writeHTMLRow(&sb, d.Name, strings.Join(d.Versions, ", "))
		}
		sb.WriteString("</table>\n")
	}

	sb.WriteString("<footer>Report produced by <strong>sbomlyze</strong> — SBOM diff &amp; analysis tool</footer>\n")
	sb.WriteString("</body>\n</html>\n")

	return sb.String()
}

func writeHTMLOverview(sb *strings.Builder, overview analysis.DiffOverview) {
	b := overview.Before
	a := overview.After

	sb.WriteString("<h2>SBOM Comparison</h2>\n<table>\n")
	sb.WriteString("<tr><th></th><th>Before</th><th>After</th></tr>\n")
	fmt.Fprintf(sb, "<tr><td><strong>File</strong></td><td>%s</td><td>%s</td></tr>\n",
		html.EscapeString(filepath.Base(b.FileName)), html.EscapeString(filepath.Base(a.FileName)))
	fmt.Fprintf(sb, "<tr><td><strong>File Size</strong></td><td>%s</td><td>%s</td></tr>\n",
		formatFileSize(b.FileSize), formatFileSize(a.FileSize))
	fmt.Fprintf(sb, "<tr><td><strong>Format</strong></td><td>%s</td><td>%s</td></tr>\n",
		html.EscapeString(orNone(b.Info.ToolName)), html.EscapeString(orNone(a.Info.ToolName)))
	fmt.Fprintf(sb, "<tr><td><strong>Components</strong></td><td>%d</td><td>%d</td></tr>\n",
		b.Stats.TotalComponents, a.Stats.TotalComponents)
	fmt.Fprintf(sb, "<tr><td><strong>PURL Coverage</strong></td><td>%s</td><td>%s</td></tr>\n",
		formatPct(b.Stats.WithPURL, b.Stats.TotalComponents),
		formatPct(a.Stats.WithPURL, a.Stats.TotalComponents))
	fmt.Fprintf(sb, "<tr><td><strong>License Coverage</strong></td><td>%s</td><td>%s</td></tr>\n",
		formatPct(b.Stats.TotalComponents-b.Stats.WithoutLicense, b.Stats.TotalComponents),
		formatPct(a.Stats.TotalComponents-a.Stats.WithoutLicense, a.Stats.TotalComponents))
	fmt.Fprintf(sb, "<tr><td><strong>Hash Coverage</strong></td><td>%s</td><td>%s</td></tr>\n",
		formatPct(b.Stats.WithHashes, b.Stats.TotalComponents),
		formatPct(a.Stats.WithHashes, a.Stats.TotalComponents))
	sb.WriteString("</table>\n")
}

func writeHTMLSummaryCards(sb *strings.Builder, result analysis.DiffResult) {
	sb.WriteString("<div class=\"summary-grid\">\n")
	writeHTMLCard(sb, fmt.Sprintf("%d", len(result.Added)), "Added")
	writeHTMLCard(sb, fmt.Sprintf("%d", len(result.Removed)), "Removed")
	writeHTMLCard(sb, fmt.Sprintf("%d", len(result.Changed)), "Changed")
	if result.DriftSummary != nil && result.DriftSummary.IntegrityDrift > 0 {
		writeHTMLCardStyled(sb, fmt.Sprintf("%d", result.DriftSummary.IntegrityDrift), "Integrity Drift", "var(--red)")
	}
	sb.WriteString("</div>\n")
}

func writeHTMLFindings(sb *strings.Builder, findings analysis.KeyFindings) {
	sb.WriteString("<h2>Key Findings</h2>\n")
	for _, f := range findings.Findings {
		fmt.Fprintf(sb, "<div class=\"finding\">%s %s</div>\n",
			html.EscapeString(f.Icon), html.EscapeString(f.Message))
	}
}

func writeHTMLDriftSummary(sb *strings.Builder, result analysis.DiffResult) {
	ds := result.DriftSummary
	sb.WriteString("<h2>Drift Summary</h2>\n<table>\n")
	sb.WriteString("<tr><th>Type</th><th>Count</th><th>Status</th></tr>\n")

	fmt.Fprintf(sb, "<tr><td>Version</td><td>%d</td><td><span class=\"badge badge-ok\">✅ OK</span></td></tr>\n", ds.VersionDrift)

	intStatus := "<span class=\"badge badge-ok\">✅ OK</span>"
	if ds.IntegrityDrift > 0 {
		intStatus = "<span class=\"badge badge-error\">⚠️ Review Required</span>"
	}
	fmt.Fprintf(sb, "<tr><td>Integrity</td><td>%d</td><td>%s</td></tr>\n", ds.IntegrityDrift, intStatus)
	fmt.Fprintf(sb, "<tr><td>Metadata</td><td>%d</td><td><span class=\"badge badge-ok\">✅ OK</span></td></tr>\n", ds.MetadataDrift)
	sb.WriteString("</table>\n")
}

func writeHTMLDepthSummary(sb *strings.Builder, result analysis.DiffResult) {
	ds := result.Dependencies.DepthSummary
	sb.WriteString("<h2>New Dependencies by Depth</h2>\n<table>\n")
	sb.WriteString("<tr><th>Depth</th><th>Count</th><th>Risk</th></tr>\n")
	fmt.Fprintf(sb, "<tr><td>1 (direct)</td><td>%d</td><td><span class=\"badge badge-ok\">Low</span></td></tr>\n", ds.Depth1)
	fmt.Fprintf(sb, "<tr><td>2</td><td>%d</td><td><span class=\"badge badge-warn\">Medium</span></td></tr>\n", ds.Depth2)

	risk := "<span class=\"badge badge-warn\">Medium</span>"
	if ds.Depth3Plus > 0 {
		risk = "<span class=\"badge badge-error\">High</span>"
	}
	fmt.Fprintf(sb, "<tr><td>3+</td><td>%d</td><td>%s</td></tr>\n", ds.Depth3Plus, risk)
	sb.WriteString("</table>\n")
}

func writeHTMLViolations(sb *strings.Builder, violations []policy.Violation) {
	var errors, warnings []policy.Violation
	for _, v := range violations {
		if v.Severity == policy.SeverityError {
			errors = append(errors, v)
		} else {
			warnings = append(warnings, v)
		}
	}

	if len(errors) > 0 {
		sb.WriteString("<h2>❌ Policy Errors</h2>\n<table>\n")
		sb.WriteString("<tr><th>Rule</th><th>Message</th></tr>\n")
		for _, v := range errors {
			writeHTMLRow(sb, html.EscapeString(v.Rule), html.EscapeString(v.Message))
		}
		sb.WriteString("</table>\n")
	}

	if len(warnings) > 0 {
		sb.WriteString("<h2>⚠️ Policy Warnings</h2>\n<table>\n")
		sb.WriteString("<tr><th>Rule</th><th>Message</th></tr>\n")
		for _, v := range warnings {
			writeHTMLRow(sb, html.EscapeString(v.Rule), html.EscapeString(v.Message))
		}
		sb.WriteString("</table>\n")
	}
}

func writeHTMLComponentSection(sb *strings.Builder, title string, comps []sbom.Component, class string) {
	fmt.Fprintf(sb, "<details>\n<summary>%s (%d)</summary>\n<table>\n",
		html.EscapeString(title), len(comps))
	sb.WriteString("<tr><th>Name</th><th>Version</th><th>Type</th><th>License</th></tr>\n")
	for _, c := range comps {
		ptype := analysis.ExtractPURLType(c.PURL)
		lic := strings.Join(c.Licenses, ", ")
		if lic == "" {
			lic = "—"
		}
		fmt.Fprintf(sb, "<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
			html.EscapeString(c.Name), html.EscapeString(c.Version),
			html.EscapeString(ptype), html.EscapeString(lic))
	}
	sb.WriteString("</table>\n</details>\n")
}

func writeHTMLChangedSection(sb *strings.Builder, changed []analysis.ChangedComponent) {
	fmt.Fprintf(sb, "<details>\n<summary>🔄 Changed Components (%d)</summary>\n<table>\n", len(changed))
	sb.WriteString("<tr><th>Name</th><th>Before</th><th>After</th><th>Drift</th></tr>\n")
	for _, c := range changed {
		drift := "—"
		driftClass := ""
		if c.Drift != nil {
			switch c.Drift.Type {
			case analysis.DriftTypeIntegrity:
				drift = "⚠️ Integrity"
				driftClass = "badge-error"
			case analysis.DriftTypeVersion:
				drift = "📦 Version"
				driftClass = "badge-info"
			case analysis.DriftTypeMetadata:
				drift = "📝 Metadata"
				driftClass = "badge-warn"
			}
		}
		driftHTML := html.EscapeString(drift)
		if driftClass != "" {
			driftHTML = fmt.Sprintf("<span class=\"badge %s\">%s</span>", driftClass, html.EscapeString(drift))
		}
		fmt.Fprintf(sb, "<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n",
			html.EscapeString(c.Name), html.EscapeString(c.Before.Version),
			html.EscapeString(c.After.Version), driftHTML)
	}
	sb.WriteString("</table>\n</details>\n")
}

func writeHTMLRow(sb *strings.Builder, col1, col2 string) {
	fmt.Fprintf(sb, "<tr><td>%s</td><td>%s</td></tr>\n", col1, col2)
}

func writeHTMLCard(sb *strings.Builder, num, label string) {
	fmt.Fprintf(sb, "<div class=\"summary-card\"><div class=\"num\">%s</div><div class=\"label\">%s</div></div>\n",
		html.EscapeString(num), html.EscapeString(label))
}

func writeHTMLCardStyled(sb *strings.Builder, num, label, color string) {
	fmt.Fprintf(sb, "<div class=\"summary-card\" style=\"border-color: %s;\"><div class=\"num\" style=\"color: %s;\">%s</div><div class=\"label\">%s</div></div>\n",
		color, color, html.EscapeString(num), html.EscapeString(label))
}
