package output

import (
	"fmt"
	"strings"
	"time"

	"github.com/rezmoss/sbomlyze/internal/analysis"
	"github.com/rezmoss/sbomlyze/internal/policy"
)

// GenerateMarkdown creates a Markdown report for PR comments
func GenerateMarkdown(result analysis.DiffResult, violations []policy.Violation) string {
	var sb strings.Builder

	sb.WriteString("## 📦 SBOM Diff Report\n\n")

	// Summary table
	sb.WriteString("### Summary\n\n")
	sb.WriteString("| Metric | Count |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Added | %d |\n", len(result.Added)))
	sb.WriteString(fmt.Sprintf("| Removed | %d |\n", len(result.Removed)))
	sb.WriteString(fmt.Sprintf("| Changed | %d |\n", len(result.Changed)))

	// Drift summary
	if result.DriftSummary != nil {
		sb.WriteString("\n### Drift Summary\n\n")
		sb.WriteString("| Type | Count | Status |\n")
		sb.WriteString("|------|-------|--------|\n")

		versionStatus := "✅"
		sb.WriteString(fmt.Sprintf("| Version | %d | %s |\n", result.DriftSummary.VersionDrift, versionStatus))

		integrityStatus := "✅"
		if result.DriftSummary.IntegrityDrift > 0 {
			integrityStatus = "⚠️ **Review Required**"
		}
		sb.WriteString(fmt.Sprintf("| Integrity | %d | %s |\n", result.DriftSummary.IntegrityDrift, integrityStatus))

		metadataStatus := "✅"
		sb.WriteString(fmt.Sprintf("| Metadata | %d | %s |\n", result.DriftSummary.MetadataDrift, metadataStatus))
	}

	// Dependency depth summary
	if result.Dependencies != nil && result.Dependencies.DepthSummary != nil {
		ds := result.Dependencies.DepthSummary
		sb.WriteString("\n### New Dependencies by Depth\n\n")
		sb.WriteString("| Depth | Count | Risk |\n")
		sb.WriteString("|-------|-------|------|\n")
		sb.WriteString(fmt.Sprintf("| 1 (direct) | %d | Low |\n", ds.Depth1))
		sb.WriteString(fmt.Sprintf("| 2 | %d | Medium |\n", ds.Depth2))

		depth3Risk := "Medium"
		if ds.Depth3Plus > 0 {
			depth3Risk = "⚠️ **High**"
		}
		sb.WriteString(fmt.Sprintf("| 3+ | %d | %s |\n", ds.Depth3Plus, depth3Risk))
	}

	// Policy violations
	if len(violations) > 0 {
		var errors, warnings []policy.Violation
		for _, v := range violations {
			if v.Severity == policy.SeverityError {
				errors = append(errors, v)
			} else {
				warnings = append(warnings, v)
			}
		}

		if len(errors) > 0 {
			sb.WriteString("\n### ❌ Policy Errors\n\n")
			for _, v := range errors {
				sb.WriteString(fmt.Sprintf("- **%s**: %s\n", v.Rule, v.Message))
			}
		}

		if len(warnings) > 0 {
			sb.WriteString("\n### ⚠️ Policy Warnings\n\n")
			for _, v := range warnings {
				sb.WriteString(fmt.Sprintf("- **%s**: %s\n", v.Rule, v.Message))
			}
		}
	}

	// Added components (collapsible)
	if len(result.Added) > 0 {
		sb.WriteString("\n<details>\n")
		sb.WriteString(fmt.Sprintf("<summary>➕ Added Components (%d)</summary>\n\n", len(result.Added)))
		sb.WriteString("| Name | Version |\n")
		sb.WriteString("|------|--------|\n")
		for _, c := range result.Added {
			sb.WriteString(fmt.Sprintf("| %s | %s |\n", c.Name, c.Version))
		}
		sb.WriteString("\n</details>\n")
	}

	// Removed components (collapsible)
	if len(result.Removed) > 0 {
		sb.WriteString("\n<details>\n")
		sb.WriteString(fmt.Sprintf("<summary>➖ Removed Components (%d)</summary>\n\n", len(result.Removed)))
		sb.WriteString("| Name | Version |\n")
		sb.WriteString("|------|--------|\n")
		for _, c := range result.Removed {
			sb.WriteString(fmt.Sprintf("| %s | %s |\n", c.Name, c.Version))
		}
		sb.WriteString("\n</details>\n")
	}

	// Changed components (collapsible)
	if len(result.Changed) > 0 {
		sb.WriteString("\n<details>\n")
		sb.WriteString(fmt.Sprintf("<summary>🔄 Changed Components (%d)</summary>\n\n", len(result.Changed)))
		sb.WriteString("| Name | Before | After | Drift |\n")
		sb.WriteString("|------|--------|-------|-------|\n")
		for _, c := range result.Changed {
			drift := ""
			if c.Drift != nil {
				switch c.Drift.Type {
				case analysis.DriftTypeIntegrity:
					drift = "⚠️ Integrity"
				case analysis.DriftTypeVersion:
					drift = "📦 Version"
				case analysis.DriftTypeMetadata:
					drift = "📝 Metadata"
				}
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", c.Name, c.Before.Version, c.After.Version, drift))
		}
		sb.WriteString("\n</details>\n")
	}

	// Footer
	sb.WriteString("\n---\n")
	sb.WriteString(fmt.Sprintf("*Generated by [sbomlyze](https://github.com/rezmoss/sbomlyze) at %s*\n", time.Now().UTC().Format(time.RFC3339)))

	return sb.String()
}
